## Figures:
extdata/tables_and_figures/figure1.png: extdata/tables_and_figures/figure1.pdf
	magick -density 300 tables_and_figures/figure1.pdf -quality 100 \
	-background white -alpha remove \
	-strip -define png:exclude-chunk=time extdata/tables_and_figures/figure1.png

extdata/tables_and_figures/figure2.png: extdata/tables_and_figures/figure2.pdf
	magick -density 300 tables_and_figures/figure2.pdf -quality 100 \
	-background white -alpha remove \
	-strip -define png:exclude-chunk=time extdata/tables_and_figures/figure2.png
